-- MySQL Script generated by MySQL Workbench
-- Sun 24 Oct 2021 12:30:18 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `codigo_editora` INT NOT NULL,
  `nome_editora` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_editora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`area_conhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`area_conhecimento` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `idautor` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `paisnascimento` VARCHAR(45) NULL,
  `biografia` VARCHAR(4096) NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livro` (
  `id` INT NOT NULL,
  `titulo_livro` VARCHAR(200) NULL,
  `numero_edicao` INT NULL,
  `ano_edicao` INT NULL,
  `codigo_editora` INT NULL,
  `idioma` VARCHAR(45) NULL,
  `area_conhecimento` INT NULL,
  `preco` FLOAT NULL,
  `ISBN` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`exemplar` (
  `id` INT NOT NULL,
  `id_livro` VARCHAR(45) NULL,
  `ISBN` VARCHAR(45) NULL,
  `sequencia` INT NULL,
  `situacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `rg` INT NULL,
  `data_nascimento` DATE NULL,
  `sexo` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cep` INT NULL,
  `logradouro` VARCHAR(45) NULL,
  `num` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimos` (
  `idexemplar` INT NOT NULL,
  `idusuario` VARCHAR(45) NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `data_prevista_devolucao` DATE NULL,
  `data_devolucao` DATE NULL,
  `hora_devolucao` VARCHAR(45) NULL,
  PRIMARY KEY (`idexemplar`, `idusuario`, `data_emprestimo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autoria` (
  `id_livro` INT NOT NULL,
  `id_autor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_livro`, `id_autor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
